// Données des pages locales /estimation-immobiliere/[slug]
// Prix : fourchettes indicatives €/m² (appartements anciens en bon état, 1er semestre 2026).
// Les prix parisiens reprennent ceux du tableau /prix-m2-paris.

export const PARIS = [
  {
    slug: "paris-1", kind: "paris", name: "Paris 1er", full: "1er arrondissement de Paris", cp: "75001",
    min: 10500, max: 14000, trend: "stable",
    intro: "Le 1er arrondissement, cœur historique de Paris entre le Louvre, les Tuileries et les Halles, est l'un des plus petits marchés résidentiels de la capitale : peu de logements, beaucoup de commerces et de bureaux. Chaque vente y est rare et chaque bien se compare à une poignée de transactions seulement — d'où l'importance d'une estimation faite par quelqu'un qui connaît les immeubles, pas seulement les moyennes.",
    quartiers: [
      ["Palais-Royal / Louvre", "Adresses rares et prisées, immeubles XVIIe-XVIIIe, clientèle internationale."],
      ["Place Vendôme / Saint-Honoré", "Marché de prestige, petites copropriétés, forte valeur des étages nobles."],
      ["Les Halles", "Plus animé, studios et deux-pièces d'investissement, bruit à évaluer rue par rue."],
      ["Place Dauphine / Île de la Cité", "Micro-marché d'exception, très peu d'offres chaque année."],
    ],
    bati: "Immeubles anciens (XVIIe au XIXe siècle), souvent sans ascenseur dans les plus petits, planchers bois et poutres apparentes ; beaucoup de logements sous les toits et de surfaces atypiques.",
    acheteurs: "Investisseurs, pied-à-terre, acquéreurs étrangers (clientèle du réseau Leggett) et cadres qui veulent vivre dans l'hyper-centre.",
    vigilance: "Nuisances (Halles, rue de Rivoli), absence d'ascenseur, DPE souvent faible dans l'ancien, règles strictes sur la location meublée touristique à Paris : autant de points qui pèsent sur le prix et qu'une estimation sérieuse doit intégrer.",
    transports: "Châtelet–Les Halles (RER A, B, D, métro 1, 4, 7, 11, 14), Louvre-Rivoli, Tuileries, Palais-Royal.",
    faq: [
      { q: "Le 1er arrondissement fait-il partie de « Paris Centre » ?", a: "Oui. Depuis 2020, les 1er, 2e, 3e et 4e arrondissements sont regroupés administrativement sous le nom de Paris Centre, mais les codes postaux (75001 à 75004) et les micro-marchés immobiliers restent distincts. Un appartement près du Palais-Royal ne s'estime pas comme un studio aux Halles." },
      { q: "Un appartement sans ascenseur perd-il beaucoup de valeur dans le 1er ?", a: "Au-delà du 3e étage, l'absence d'ascenseur réduit généralement la valeur et le nombre d'acheteurs. Dans le 1er, la rareté de l'offre atténue parfois l'effet, surtout pour les petites surfaces de caractère. Marie l'évalue au cas par cas, à partir des ventes réelles de l'immeuble et de la rue." },
    ],
    near: ["paris-2", "paris-4", "paris-8", "paris-6"],
  },
  {
    slug: "paris-2", kind: "paris", name: "Paris 2e", full: "2e arrondissement de Paris", cp: "75002",
    min: 10000, max: 13000, trend: "stable",
    intro: "Plus petit arrondissement de Paris, le 2e vit au rythme du Sentier, de la Bourse et de la rue Montorgueil. Longtemps dominé par les bureaux et la confection, il s'est profondément transformé : lofts, appartements rénovés et passages couverts attirent une clientèle jeune et aisée.",
    quartiers: [
      ["Montorgueil / Saint-Sauveur", "Rue piétonne, commerces de bouche, très forte demande sur les 2 et 3 pièces."],
      ["Sentier", "Anciens ateliers transformés en lofts, surfaces atypiques à estimer finement."],
      ["Bourse / Vivienne", "Immeubles bourgeois, galeries Vivienne et Colbert, marché plus calme."],
      ["Bonne-Nouvelle", "Plus abordable, en rattrapage, proche des Grands Boulevards."],
    ],
    bati: "Immeubles XVIIIe-XIXe, anciens ateliers et locaux reconvertis en logements, cours intérieures, parfois de belles hauteurs sous plafond.",
    acheteurs: "Jeunes actifs à fort pouvoir d'achat, entrepreneurs, investisseurs en petites surfaces.",
    vigilance: "Vérifier la destination des lots (un ancien local d'activité transformé doit être régulièrement déclaré en habitation), la luminosité en fond de cour et le bruit des rues festives.",
    transports: "Sentier, Bourse, Grands Boulevards, Réaumur–Sébastopol (lignes 3, 4, 8, 9), Châtelet à proximité.",
    faq: [
      { q: "Un loft du Sentier s'estime-t-il comme un appartement classique ?", a: "Pas tout à fait. La surface Carrez, la hauteur sous plafond, la lumière et surtout la régularité du changement d'usage (local d'activité vers habitation) comptent beaucoup. Un loft bien régularisé peut dépasser la moyenne de l'arrondissement ; un lot à la situation administrative floue sera pénalisé par les acheteurs et leurs banques." },
      { q: "Le 2e est-il un bon secteur pour vendre un studio ?", a: "Oui, la demande des investisseurs et des pied-à-terre y est soutenue. Le prix au m² d'un studio est souvent supérieur à celui d'un grand appartement du même immeuble. Le DPE et les charges de copropriété restent décisifs pour les investisseurs." },
    ],
    near: ["paris-1", "paris-3", "paris-9", "paris-10"],
  },
  {
    slug: "paris-3", kind: "paris", name: "Paris 3e", full: "3e arrondissement de Paris", cp: "75003",
    min: 10500, max: 13500, trend: "hausse",
    intro: "Le Haut Marais est devenu l'un des secteurs les plus convoités de Paris : hôtels particuliers, galeries, boutiques de créateurs et rues calmes. Le 3e conjugue le charme de l'ancien et une vraie vie de quartier, ce qui soutient les prix même lorsque le marché parisien marque le pas.",
    quartiers: [
      ["Haut Marais / Enfants-Rouges", "Marché couvert, rues de Bretagne et de Turenne : adresse très recherchée."],
      ["Archives / Francs-Bourgeois", "Hôtels particuliers, musées, appartements de caractère."],
      ["Arts-et-Métiers", "Un peu plus abordable, bonne desserte, immeubles faubouriens."],
      ["Square du Temple", "Familles et jeunes cadres, apprécié pour son square et son calme relatif."],
    ],
    bati: "Hôtels particuliers divisés, immeubles XVIIe-XVIIIe, poutres apparentes, parquets anciens ; une grande partie du secteur relève du Plan de sauvegarde et de mise en valeur du Marais.",
    acheteurs: "Couples actifs, créatifs, acquéreurs internationaux sensibles au charme historique.",
    vigilance: "Le Plan de sauvegarde du Marais encadre strictement les travaux : un bien à rénover lourdement doit être estimé en tenant compte de ces contraintes. L'exposition et l'étage font aussi de gros écarts dans ces rues étroites.",
    transports: "Arts-et-Métiers, Temple, Filles du Calvaire, Saint-Sébastien–Froissart (lignes 3, 8, 11), République à proximité.",
    faq: [
      { q: "Le Plan de sauvegarde du Marais a-t-il un impact sur le prix ?", a: "Il protège le cadre qui fait la valeur du quartier, donc il la soutient. Mais il limite certains travaux (menuiseries, façades, surélévations, parfois distribution intérieure). Pour un bien à rénover, l'estimation doit intégrer ce cadre réglementaire et le coût réel des travaux autorisés." },
      { q: "Quels biens se vendent le mieux dans le 3e ?", a: "Les deux et trois pièces de caractère (poutres, cheminées, parquet) dans les étages élevés et lumineux, avec ascenseur. Ils trouvent généralement preneur rapidement lorsque le prix est en ligne avec les ventes récentes de la rue." },
    ],
    near: ["paris-4", "paris-2", "paris-10", "paris-11"],
  },
  {
    slug: "paris-4", kind: "paris", name: "Paris 4e", full: "4e arrondissement de Paris", cp: "75004",
    min: 11000, max: 14500, trend: "stable",
    intro: "Entre le Marais, l'Hôtel de Ville, l'île Saint-Louis et une partie de l'île de la Cité, le 4e réunit certaines des adresses les plus emblématiques de Paris. L'offre y est rare, la clientèle internationale très présente, et les écarts de prix entre deux immeubles peuvent être considérables.",
    quartiers: [
      ["Île Saint-Louis", "Quais, vues sur Seine, marché d'exception très étroit."],
      ["Saint-Paul / Place des Vosges", "Hôtels particuliers, cours pavées, forte demande internationale."],
      ["Beaubourg / Saint-Merri", "Plus animé, studios et 2 pièces, bruit à qualifier."],
      ["Arsenal", "Plus résidentiel, proche du bassin de l'Arsenal et de Bastille."],
    ],
    bati: "Bâti très ancien (XVIe-XVIIIe siècles pour une partie), secteur sauvegardé, hauteurs sous plafond variables, ascenseurs absents dans certains immeubles.",
    acheteurs: "Acquéreurs internationaux, pied-à-terre, cadres et professions libérales.",
    vigilance: "Vue sur Seine, étage et luminosité peuvent justifier des primes importantes ; à l'inverse, un rez-de-chaussée sur rue passante ou un étage élevé sans ascenseur se négocie nettement. Le long des quais, le risque inondation (PPRI) figure dans l'état des risques.",
    transports: "Saint-Paul, Hôtel de Ville, Pont Marie, Sully–Morland (lignes 1, 7, 11), Châtelet à proximité.",
    faq: [
      { q: "Une vue sur Seine augmente-t-elle vraiment la valeur ?", a: "Oui, souvent de façon significative, surtout en étage élevé sur l'île Saint-Louis ou les quais. Mais il n'existe pas de pourcentage fixe : Marie compare avec les ventes récentes de biens comparables avec et sans vue pour chiffrer cette prime de manière défendable." },
      { q: "Les biens proches de la Seine sont-ils concernés par le risque d'inondation ?", a: "Une partie du 4e est couverte par le Plan de prévention du risque inondation (PPRI) de Paris. L'information figure dans l'état des risques remis à l'acquéreur. L'impact sur le prix est généralement modéré pour les étages, plus sensible pour les caves et rez-de-chaussée." },
    ],
    near: ["paris-3", "paris-1", "paris-5", "paris-11"],
  },
  {
    slug: "paris-5", kind: "paris", name: "Paris 5e", full: "5e arrondissement de Paris", cp: "75005",
    min: 10500, max: 14000, trend: "stable",
    intro: "Quartier latin, Sorbonne, Panthéon, jardin des Plantes : le 5e est l'arrondissement du savoir et d'une vie de quartier très parisienne. Recherché par les familles, les universitaires et les acheteurs étrangers, il affiche des prix élevés et une grande stabilité.",
    quartiers: [
      ["Sorbonne / Panthéon", "Adresses prestigieuses, immeubles bourgeois, forte demande familiale."],
      ["Mouffetard / Contrescarpe", "Charme village, petites surfaces très demandées."],
      ["Jardin des Plantes", "Calme, verdure, grands appartements familiaux."],
      ["Val-de-Grâce", "Résidentiel, proche du Luxembourg, immeubles haussmanniens."],
    ],
    bati: "Haussmannien et immeubles plus anciens autour de la Contrescarpe, beaucoup de pierre de taille, quelques résidences plus récentes vers Censier.",
    acheteurs: "Familles attachées aux établissements scolaires réputés du secteur, universitaires, investisseurs en studios étudiants, acheteurs internationaux.",
    vigilance: "Les petites surfaces sont très liquides mais les investisseurs regardent de près le DPE et les charges. Pour les grands appartements, l'étage, l'ascenseur et la proximité du Luxembourg ou du Panthéon font la différence.",
    transports: "RER B (Luxembourg, Port-Royal, Saint-Michel), RER C, lignes 7 et 10 (Place Monge, Censier–Daubenton, Maubert–Mutualité, Cardinal Lemoine).",
    faq: [
      { q: "Pourquoi les prix sont-ils si stables dans le 5e ?", a: "Parce que l'offre est structurellement rare et que la demande est diversifiée : familles, universitaires, investisseurs et acheteurs internationaux. Même dans les phases de correction, les biens de qualité du 5e ont moins reculé que la moyenne parisienne." },
      { q: "Un studio étudiant se vend-il facilement dans le 5e ?", a: "Oui, s'il est bien situé et correctement classé au DPE. Depuis que les logements classés G ne peuvent plus être proposés à la location, un studio énergivore perd une partie de ses acheteurs investisseurs : il vaut parfois mieux chiffrer les travaux avant la mise en vente." },
    ],
    near: ["paris-6", "paris-4", "paris-13", "paris-14"],
  },
  {
    slug: "paris-6", kind: "paris", name: "Paris 6e", full: "6e arrondissement de Paris", cp: "75006",
    min: 12500, max: 16000, trend: "hausse",
    intro: "Saint-Germain-des-Prés, Odéon, jardin du Luxembourg : le 6e est l'un des deux arrondissements les plus chers de Paris. Clientèle exigeante, biens d'exception, forte présence internationale — c'est un marché où l'estimation se joue à l'immeuble, voire à l'étage près.",
    quartiers: [
      ["Saint-Germain-des-Prés", "Adresse mythique, marché du luxe, acheteurs du monde entier."],
      ["Odéon / Saint-Sulpice", "Immeubles XVIIe-XVIIIe, très forte demande."],
      ["Luxembourg / Notre-Dame-des-Champs", "Familles, grands appartements bourgeois, vue jardin très valorisée."],
      ["Monnaie / Quai Conti", "Quais, vues sur Seine, offre extrêmement rare."],
    ],
    bati: "Bâti ancien de grande qualité, immeubles XVIIe au XIXe, hôtels particuliers, appartements avec parquet, moulures et cheminées.",
    acheteurs: "Acquéreurs internationaux, familles aisées, professions libérales ; la clientèle Leggett (britannique, américaine, européenne) y est particulièrement active.",
    vigilance: "Vue sur le Luxembourg ou la Seine, étage noble, calme sur cour : les primes sont réelles mais doivent être justifiées par des ventes comparables. Un prix trop ambitieux reste visible longtemps et dessert le vendeur, même ici.",
    transports: "Saint-Germain-des-Prés, Odéon, Saint-Sulpice, Mabillon (lignes 4 et 10), RER B Luxembourg.",
    faq: [
      { q: "Le 6e est-il l'arrondissement le plus cher de Paris ?", a: "Il se dispute cette place avec le 7e. Selon les rues, les biens d'exception dépassent nettement les moyennes affichées. C'est précisément pour cela qu'une estimation fondée sur les ventes réelles de l'immeuble et de la rue est indispensable." },
      { q: "Comment toucher les acheteurs étrangers pour un appartement du 6e ?", a: "Grâce à l'affiliation Leggett, votre bien est présenté à une clientèle internationale qui recherche spécifiquement la Rive gauche. Marie organise les visites, y compris à distance en vidéo, et accompagne ces acquéreurs jusqu'au notaire." },
    ],
    near: ["paris-7", "paris-5", "paris-14", "paris-15"],
  },
  {
    slug: "paris-7", kind: "paris", name: "Paris 7e", full: "7e arrondissement de Paris", cp: "75007",
    min: 12000, max: 15500, trend: "stable",
    intro: "Invalides, Tour Eiffel, faubourg Saint-Germain : le 7e est l'arrondissement des ministères, des ambassades et des grandes familles parisiennes. Très résidentiel, calme et verdoyant, il attire une clientèle patrimoniale qui recherche la qualité avant tout.",
    quartiers: [
      ["Faubourg Saint-Germain / Rue du Bac", "Hôtels particuliers, grands appartements, adresses institutionnelles."],
      ["Invalides / École militaire", "Avenues larges, immeubles haussmanniens, familles."],
      ["Gros-Caillou / Rue Cler", "Vie de quartier, commerces, très demandé."],
      ["Champ-de-Mars", "Vues iconiques, forte demande internationale."],
    ],
    bati: "Haussmannien et post-haussmannien de standing, immeubles en pierre de taille avec gardien, grandes réceptions ; quelques immeubles des années 1930 et 1970 plus accessibles.",
    acheteurs: "Familles, diplomates, cadres dirigeants, acquéreurs internationaux à la recherche d'un pied-à-terre d'exception.",
    vigilance: "Vue sur la Tour Eiffel, étage élevé, balcon filant : fortes primes. À l'inverse, les immeubles des années 1970 ou les rez-de-chaussée se négocient nettement sous la moyenne. Le détail de l'immeuble compte autant que l'arrondissement.",
    transports: "Lignes 8, 10, 12 et 13 (École Militaire, Varenne, Rue du Bac, Solférino, Sèvres–Babylone), RER C (Invalides, Musée d'Orsay, Champ de Mars).",
    faq: [
      { q: "Combien vaut une vue sur la Tour Eiffel dans le 7e ?", a: "C'est l'un des critères les plus valorisants de Paris, mais sa valeur dépend de la qualité de la vue (partielle ou dégagée), de l'étage et des pièces concernées. Marie s'appuie sur des ventes comparables pour chiffrer cet avantage sans le surestimer." },
      { q: "Un appartement des années 1970 dans le 7e vaut-il le prix du quartier ?", a: "Généralement non : les acheteurs du 7e privilégient l'ancien de caractère. Un immeuble plus récent offre toutefois des atouts (parking, ascenseur, balcon, meilleur DPE) qu'il faut mettre en avant dans la stratégie de prix." },
    ],
    near: ["paris-6", "paris-15", "paris-8", "paris-16"],
  },
  {
    slug: "paris-8", kind: "paris", name: "Paris 8e", full: "8e arrondissement de Paris", cp: "75008",
    min: 10500, max: 14000, trend: "stable",
    intro: "Champs-Élysées, Madeleine, parc Monceau : le 8e mêle prestige international, bureaux et quartiers résidentiels très bourgeois. Le marché y est contrasté entre les rues d'affaires et les secteurs familiaux autour de Monceau et de l'Europe.",
    quartiers: [
      ["Parc Monceau", "Résidentiel haut de gamme, grands appartements familiaux."],
      ["Triangle d'or / Champs-Élysées", "Luxe, pied-à-terre internationaux, biens d'exception."],
      ["Madeleine / Saint-Augustin", "Mixte bureaux-logements, clientèle d'affaires."],
      ["Europe / Saint-Lazare", "Plus abordable, très bien desservi, immeubles haussmanniens."],
    ],
    bati: "Haussmannien de prestige, hôtels particuliers, nombreux immeubles de bureaux ; les appartements familiaux sont concentrés côté Monceau et Europe.",
    acheteurs: "Clientèle internationale, dirigeants, familles aisées recherchant le calme de Monceau.",
    vigilance: "Dans les rues très tertiaires, le quartier est plus calme le soir et le week-end : un point à anticiper pour certains acheteurs. La proximité du parc Monceau est un vrai moteur de valeur.",
    transports: "Saint-Lazare (RER E, lignes 3, 12, 13, 14), Charles de Gaulle–Étoile (RER A), Madeleine, Monceau, Miromesnil.",
    faq: [
      { q: "Pourquoi les prix sont-ils si différents à l'intérieur du 8e ?", a: "Parce que l'arrondissement juxtapose des rues de bureaux, un secteur de luxe très international et des quartiers familiaux autour du parc Monceau. Le prix moyen de l'arrondissement ne veut pas dire grand-chose : seule l'analyse de votre rue et de votre immeuble est pertinente." },
      { q: "Les acheteurs étrangers sont-ils encore présents dans le 8e ?", a: "Oui, notamment pour les pied-à-terre haut de gamme. Le réseau Leggett permet de présenter votre bien à ces acquéreurs, en complément des portails français." },
    ],
    near: ["paris-17", "paris-16", "paris-9", "paris-1"],
  },
  {
    slug: "paris-9", kind: "paris", name: "Paris 9e", full: "9e arrondissement de Paris", cp: "75009",
    min: 9500, max: 12500, trend: "hausse",
    intro: "Du quartier Saint-Georges à South Pigalle, le 9e s'est imposé comme l'un des arrondissements les plus demandés par les jeunes actifs et les familles. Immeubles haussmanniens, cités privées, vie de quartier animée : les prix y ont nettement progressé ces dernières années.",
    quartiers: [
      ["Saint-Georges / Nouvelle Athènes", "Hôtels particuliers, cités privées, immeubles de caractère."],
      ["South Pigalle / Rue des Martyrs", "Très prisé, forte demande sur les 2-3 pièces."],
      ["Trudaine / Rochechouart", "Avenue arborée, familles, bonne desserte."],
      ["Opéra / Chaussée-d'Antin", "Plus tertiaire, grands magasins, appartements bourgeois."],
    ],
    bati: "Haussmannien et néo-classique (Nouvelle Athènes), nombreuses cours et cités privées, appartements familiaux lumineux dans les étages.",
    acheteurs: "Jeunes couples et familles, cadres travaillant à Saint-Lazare ou à La Défense, investisseurs.",
    vigilance: "L'écart entre une rue calme de la Nouvelle Athènes et un axe bruyant (boulevards, rue de Maubeuge) est important. Balcon, ascenseur et étage élevé sont très valorisés.",
    transports: "Lignes 2, 7, 8, 9, 12, 13 (Saint-Georges, Pigalle, Notre-Dame-de-Lorette, Cadet), RER A et E à Auber / Haussmann–Saint-Lazare.",
    faq: [
      { q: "Le 9e arrondissement est-il toujours en hausse ?", a: "Il fait partie des arrondissements les plus dynamiques de Paris, porté par une demande jeune et solvable. Cela ne dispense pas d'un prix juste : les acheteurs du 9e sont bien informés et comparent en permanence." },
      { q: "Quels biens se vendent le plus vite dans le 9e ?", a: "Les deux et trois pièces rénovés, lumineux, avec ascenseur, près de la rue des Martyrs ou de Saint-Georges. Ils trouvent souvent preneur en quelques semaines lorsqu'ils sont bien présentés." },
    ],
    near: ["paris-18", "paris-10", "paris-8", "paris-2"],
  },
  {
    slug: "paris-10", kind: "paris", name: "Paris 10e", full: "10e arrondissement de Paris", cp: "75010",
    min: 8800, max: 11500, trend: "hausse",
    intro: "Canal Saint-Martin, gares du Nord et de l'Est, faubourgs animés : le 10e est un arrondissement contrasté, en forte progression depuis une quinzaine d'années. Les abords du canal et du faubourg Saint-Denis séduisent une clientèle jeune, tandis que les environs des gares restent plus accessibles.",
    quartiers: [
      ["Canal Saint-Martin", "Le secteur le plus recherché de l'arrondissement, vues sur l'eau très valorisées."],
      ["Faubourg Saint-Denis", "Animé, restaurants, petites surfaces très demandées."],
      ["Gare du Nord / Gare de l'Est", "Plus abordable, environnement à qualifier rue par rue."],
      ["Hôpital Saint-Louis / Colonel-Fabien", "Résidentiel, en rattrapage, bon potentiel."],
    ],
    bati: "Immeubles faubouriens et haussmanniens, anciens ateliers, quelques lofts ; beaucoup de petites surfaces.",
    acheteurs: "Primo-accédants, jeunes couples, investisseurs, familles attirées par le canal.",
    vigilance: "La micro-localisation fait tout : une rue proche du canal n'a rien à voir avec une rue longeant les voies ferrées. Le bruit, l'environnement immédiat et l'étage pèsent fortement dans la négociation.",
    transports: "Gare du Nord (RER B, D, E, lignes 4 et 5), Gare de l'Est, République, Jacques Bonsergent, Château-Landon.",
    faq: [
      { q: "Le 10e est-il un bon arrondissement pour vendre en 2026 ?", a: "C'est l'un des secteurs où la demande des primo-accédants est la plus forte. Les biens bien situés près du canal se vendent rapidement ; ailleurs, le prix doit être finement ajusté à la rue et à l'environnement immédiat." },
      { q: "Une vue sur le canal Saint-Martin fait-elle monter le prix ?", a: "Oui, c'est un atout recherché, surtout en étage élevé. Marie chiffre cette prime à partir des ventes comparables le long du canal pour pouvoir la défendre face aux acheteurs." },
    ],
    near: ["paris-9", "paris-11", "paris-19", "paris-3"],
  },
  {
    slug: "paris-11", kind: "paris", name: "Paris 11e", full: "11e arrondissement de Paris", cp: "75011",
    min: 9200, max: 12000, trend: "stable",
    intro: "Oberkampf, Bastille, Charonne, Voltaire : le 11e est l'un des arrondissements les plus densément peuplés et les plus vivants de Paris. Très prisé des jeunes actifs, il offre un marché liquide où les biens bien estimés partent vite.",
    quartiers: [
      ["Oberkampf / Folie-Méricourt", "Bars, restaurants, très forte demande des 25-40 ans."],
      ["Bastille / Roquette", "Animé, ateliers et cours pavées, lofts recherchés."],
      ["Voltaire / Léon-Blum", "Plus familial, haussmannien, marchés et squares."],
      ["Charonne", "Plus calme, bon rapport qualité-prix."],
    ],
    bati: "Immeubles faubouriens, cours et passages d'artisans, ateliers reconvertis, haussmannien sur les grands boulevards.",
    acheteurs: "Jeunes actifs, couples avec un premier enfant, investisseurs locatifs.",
    vigilance: "Le bruit (bars, boulevards), la luminosité des cours et l'état des parties communes font de gros écarts. Les ateliers et lofts demandent une estimation spécifique.",
    transports: "Lignes 1, 2, 3, 5, 8, 9, 11 (Bastille, Oberkampf, Voltaire, Charonne, Parmentier), République et Nation à proximité.",
    faq: [
      { q: "Un appartement sur cour vaut-il moins cher dans le 11e ?", a: "Pas forcément : sur cour, on gagne souvent en calme. Tout dépend de la luminosité. Un appartement sur cour clair en étage élevé peut se vendre aussi bien qu'un bien sur une rue bruyante." },
      { q: "Les lofts du 11e sont-ils faciles à vendre ?", a: "Ils ont une clientèle fidèle mais plus restreinte. Surface réelle, hauteur, lumière et régularité administrative du changement d'usage doivent être parfaitement documentées pour obtenir le meilleur prix." },
    ],
    near: ["paris-3", "paris-12", "paris-20", "paris-10"],
  },
  {
    slug: "paris-12", kind: "paris", name: "Paris 12e", full: "12e arrondissement de Paris", cp: "75012",
    min: 8700, max: 11000, trend: "stable",
    intro: "Bercy, Nation, Daumesnil, bois de Vincennes : le 12e est un arrondissement résidentiel, vert et familial, apprécié pour sa qualité de vie et sa desserte. Les prix y restent plus raisonnables que dans l'ouest parisien, pour des surfaces souvent plus généreuses.",
    quartiers: [
      ["Bercy / Cour Saint-Émilion", "Immeubles récents, parc de Bercy, familles."],
      ["Daumesnil / Coulée verte", "Calme, verdure, haussmannien et années 1930."],
      ["Aligre / Ledru-Rollin", "Marché d'Aligre, ambiance faubourg, très demandé."],
      ["Nation / Picpus / Bel-Air", "Résidentiel, proche du bois de Vincennes et de Saint-Mandé."],
    ],
    bati: "Grande diversité : haussmannien, immeubles en brique des années 1930, résidences des années 1970-1990 à Bercy et autour de la gare de Lyon.",
    acheteurs: "Familles, cadres travaillant gare de Lyon ou dans l'est parisien, acheteurs venant de Vincennes et Saint-Mandé.",
    vigilance: "Entre un immeuble 1930 en brique avec balcon et une résidence des années 1970, la différence de prix est réelle. Parkings et caves, plus fréquents ici, ajoutent de la valeur.",
    transports: "Gare de Lyon (RER A, D, lignes 1 et 14), Nation (RER A, lignes 1, 2, 6, 9), Bercy, Daumesnil, Porte Dorée.",
    faq: [
      { q: "Le 12e est-il un bon arrondissement pour les familles ?", a: "Oui, c'est même l'un de ses principaux atouts : espaces verts, écoles, surfaces plus grandes. Les 3 et 4 pièces familiaux y sont particulièrement recherchés." },
      { q: "Une place de parking augmente-t-elle le prix de vente ?", a: "Oui, surtout dans le 12e où beaucoup d'acheteurs ont une voiture. Elle peut être vendue avec l'appartement ou séparément ; Marie vous aide à choisir l'option la plus avantageuse." },
    ],
    near: ["paris-11", "paris-13", "paris-20", "saint-mande"],
  },
  {
    slug: "paris-13", kind: "paris", name: "Paris 13e", full: "13e arrondissement de Paris", cp: "75013",
    min: 8200, max: 10500, trend: "stable",
    intro: "Butte-aux-Cailles, Gobelins, Paris Rive Gauche, Olympiades : le 13e est l'un des arrondissements les plus variés de Paris. Entre maisons de ville, immeubles anciens et tours des années 1970, les prix peuvent varier très fortement d'une adresse à l'autre.",
    quartiers: [
      ["Butte-aux-Cailles", "Esprit village, maisons et petits immeubles, très recherché."],
      ["Gobelins / Croulebarbe", "Haussmannien, familles, bonne desserte."],
      ["Paris Rive Gauche / BnF", "Immeubles neufs et récents, meilleurs DPE."],
      ["Olympiades / Porte d'Italie", "Tours des années 1970, prix plus accessibles, charges à étudier."],
    ],
    bati: "Haussmannien autour des Gobelins, petites maisons et cités à la Butte-aux-Cailles, immeubles de grande hauteur des années 1960-70, constructions récentes à Paris Rive Gauche.",
    acheteurs: "Familles, primo-accédants, étudiants et investisseurs, cadres travaillant sur la rive gauche.",
    vigilance: "Dans les tours et grands ensembles, les charges de copropriété et les travaux votés (ravalement, isolation) pèsent lourd. Le DPE est particulièrement scruté dans cet arrondissement.",
    transports: "Lignes 5, 6, 7 et 14 (Place d'Italie, Gobelins, Olympiades, Bibliothèque François-Mitterrand), RER C, tramway T3a.",
    faq: [
      { q: "Pourquoi les prix varient-ils autant dans le 13e ?", a: "Parce que le bâti y est très hétérogène : une maison de la Butte-aux-Cailles, un haussmannien des Gobelins et un appartement dans une tour des Olympiades ne s'adressent pas aux mêmes acheteurs. L'estimation doit comparer des biens réellement comparables." },
      { q: "Des charges de copropriété élevées font-elles baisser le prix ?", a: "Oui, les acheteurs les intègrent dans leur budget mensuel. Des charges importantes ou des travaux votés doivent être présentés clairement et pris en compte dans le prix pour éviter une renégociation tardive." },
    ],
    near: ["paris-5", "paris-12", "paris-14"],
  },
  {
    slug: "paris-14", kind: "paris", name: "Paris 14e", full: "14e arrondissement de Paris", cp: "75014",
    min: 8700, max: 11500, trend: "stable",
    intro: "Montparnasse, Denfert-Rochereau, Alésia, parc Montsouris : le 14e est un arrondissement résidentiel, calme et familial, apprécié pour ses villas cachées et sa vie de quartier. Son marché est réputé stable et moins spéculatif que celui du centre.",
    quartiers: [
      ["Montparnasse / Vavin", "Proche du 6e, immeubles bourgeois, forte demande."],
      ["Denfert-Rochereau / Daguerre", "Rue piétonne, familles, très recherché."],
      ["Parc Montsouris", "Villas, maisons d'artistes, calme exceptionnel."],
      ["Pernety / Plaisance / Alésia", "Plus accessible, vie de quartier, bon potentiel."],
    ],
    bati: "Haussmannien et post-haussmannien, ateliers d'artistes, villas et maisons (villa Seurat, square de Montsouris), immeubles des années 1970 autour de Montparnasse.",
    acheteurs: "Familles, enseignants, professions libérales, acheteurs quittant le 6e pour plus d'espace.",
    vigilance: "Une partie du sous-sol du 14e est concernée par les anciennes carrières : l'information figure dans l'état des risques et doit être anticipée, en particulier pour les maisons et les projets de travaux.",
    transports: "Montparnasse (lignes 4, 6, 12, 13), Denfert-Rochereau (RER B, lignes 4 et 6), Alésia, Pernety, tramway T3a.",
    faq: [
      { q: "Les anciennes carrières du 14e posent-elles problème pour vendre ?", a: "Dans la grande majorité des cas, non : les immeubles concernés ont été consolidés. Mais l'information doit être transmise à l'acquéreur, et pour une maison ou un projet de travaux, un avis de l'Inspection générale des carrières rassure les acheteurs et leurs banques." },
      { q: "Combien vaut une maison dans le 14e ?", a: "Les maisons de ville et villas du 14e sont rares et se vendent au cas par cas, souvent bien au-delà des prix au m² des appartements. Seule une visite permet d'en estimer la valeur réelle." },
    ],
    near: ["paris-6", "paris-15", "paris-13"],
  },
  {
    slug: "paris-15", kind: "paris", name: "Paris 15e", full: "15e arrondissement de Paris", cp: "75015",
    min: 8700, max: 11500, trend: "stable",
    intro: "Plus grand et plus peuplé des arrondissements parisiens, le 15e est avant tout résidentiel et familial. Du Champ-de-Mars à la porte de Versailles, en passant par Commerce et Convention, il offre une grande diversité d'adresses et un marché très actif.",
    quartiers: [
      ["Cambronne / La Motte-Picquet", "Proche du 7e, haussmannien, prix élevés."],
      ["Commerce / Émile-Zola", "Vie de quartier, familles, très recherché."],
      ["Convention / Vaugirard", "Résidentiel, commerces, grand choix de 3-4 pièces."],
      ["Front de Seine / Beaugrenelle", "Tours des années 1970, vues sur Seine, charges à étudier."],
    ],
    bati: "Haussmannien et post-haussmannien, nombreux immeubles des années 1930 et résidences des années 1960-70, tours du Front de Seine.",
    acheteurs: "Familles avant tout, cadres, acquéreurs venant de Boulogne ou d'Issy-les-Moulineaux, investisseurs en petites surfaces.",
    vigilance: "Entre un haussmannien près du Champ-de-Mars et un appartement dans une tour du Front de Seine, les prix n'ont rien à voir. Balcon, parking et étage élevé sont des atouts majeurs dans ce secteur familial.",
    transports: "Lignes 6, 8, 10, 12, 13 (Commerce, La Motte-Picquet, Vaugirard, Convention), RER C, tramways T2 et T3a.",
    faq: [
      { q: "Le 15e est-il un bon arrondissement pour vendre un appartement familial ?", a: "C'est même son cœur de marché. Les 3 et 4 pièces bien situés, proches des écoles et du métro, sont très recherchés. Un prix juste permet souvent de vendre en quelques semaines." },
      { q: "Les appartements du Front de Seine se vendent-ils bien ?", a: "Ils ont leurs acheteurs, notamment pour les vues et les grandes surfaces, mais les charges, le DPE et les travaux de copropriété sont examinés de près. Une estimation réaliste est essentielle pour éviter un bien qui stagne." },
    ],
    near: ["paris-7", "paris-16", "paris-14", "issy-les-moulineaux"],
  },
  {
    slug: "paris-16", kind: "paris", name: "Paris 16e", full: "16e arrondissement de Paris", cp: "75016",
    min: 9200, max: 13500, trend: "stable",
    intro: "Passy, Auteuil, Trocadéro, Porte Dauphine : le 16e est l'arrondissement bourgeois et familial par excellence, avec des écarts de prix très importants d'une rue à l'autre. C'est le marché parisien où la connaissance fine des adresses fait le plus la différence.",
    quartiers: [
      ["Trocadéro / Iéna / Chaillot", "Vues Tour Eiffel, prestige, clientèle internationale."],
      ["Passy / La Muette", "Commerçant, familial, grands appartements très recherchés."],
      ["Auteuil", "Plus calme, villas et hameaux, esprit village."],
      ["Porte Dauphine / Victor-Hugo", "Beaux immeubles, proximité du bois de Boulogne."],
    ],
    bati: "Haussmannien de standing, immeubles Art nouveau et Art déco, hôtels particuliers, villas privées, immeubles des années 1960-70 plus accessibles.",
    acheteurs: "Familles, cadres dirigeants, acquéreurs internationaux, parents qui recherchent la proximité d'établissements scolaires réputés.",
    vigilance: "Un même arrondissement, des écarts considérables : un appartement rue de Passy n'a pas la valeur d'un bien sur un axe passant du sud du 16e. Étage, vue, balcon, gardien et état de l'immeuble doivent être comparés à des ventes réellement équivalentes.",
    transports: "Lignes 6, 9 et 10 (Passy, La Muette, Trocadéro, Michel-Ange, Jasmin), ligne 2 à Porte Dauphine, RER C, RER A à Charles de Gaulle–Étoile.",
    faq: [
      { q: "Pourquoi les prix du 16e varient-ils autant ?", a: "Le 16e est très étendu et hétérogène : les secteurs Trocadéro et Passy n'ont pas la même clientèle que le sud d'Auteuil. L'immeuble (haussmannien avec gardien ou résidence des années 70), l'étage et la vue comptent énormément." },
      { q: "Le réseau Leggett est-il utile pour vendre dans le 16e ?", a: "Ce n'est pas indispensable, mais c'est un vrai atout pour les biens de standing : une partie des acquéreurs du 16e vient de l'étranger ou revient d'expatriation. Leggett permet de les toucher en plus des acheteurs français." },
    ],
    near: ["paris-17", "paris-15", "paris-8", "neuilly-sur-seine", "boulogne-billancourt"],
  },
  {
    slug: "paris-17", kind: "paris", name: "Paris 17e", full: "17e arrondissement de Paris", cp: "75017",
    min: 8700, max: 12000, trend: "hausse",
    intro: "Des Ternes aux Batignolles, de la plaine Monceau aux Épinettes, le 17e est un arrondissement à deux visages : bourgeois à l'ouest, plus jeune et dynamique à l'est. Le quartier Clichy-Batignolles et le prolongement de la ligne 14 ont encore renforcé son attractivité.",
    quartiers: [
      ["Plaine Monceau / Wagram", "Haussmannien de standing, familles aisées."],
      ["Ternes / Porte Maillot", "Commerçant, résidentiel, proche de Neuilly."],
      ["Batignolles", "Esprit village, très prisé, en forte hausse."],
      ["Épinettes / Guy-Môquet", "Plus abordable, en rattrapage, bon potentiel."],
    ],
    bati: "Haussmannien et post-haussmannien à l'ouest, immeubles faubouriens et petites maisons aux Batignolles et aux Épinettes, constructions récentes à Clichy-Batignolles.",
    acheteurs: "Familles, jeunes cadres, acheteurs du 8e ou de Neuilly cherchant plus d'espace, investisseurs.",
    vigilance: "La coupure est nette entre l'ouest haussmannien et l'est plus populaire : il faut comparer à l'échelle du quartier, pas de l'arrondissement. La proximité de la ligne 14 et du parc Martin-Luther-King est un vrai plus.",
    transports: "Ligne 14 (Pont Cardinet, Porte de Clichy), lignes 2, 3 et 13, RER C, RER E à Porte Maillot, tramway T3b.",
    faq: [
      { q: "Les Batignolles sont-elles plus chères que le reste du 17e ?", a: "Le secteur a fortement progressé et rejoint souvent les prix de l'ouest de l'arrondissement pour les biens de qualité. Les Épinettes, voisines, restent plus abordables." },
      { q: "Le prolongement de la ligne 14 a-t-il fait monter les prix ?", a: "Il a amélioré l'accessibilité du nord du 17e et soutenu la demande. Dans une estimation, la distance à pied d'une station structurante est un critère réel, à pondérer avec l'immeuble et l'étage." },
    ],
    near: ["paris-8", "paris-16", "paris-18", "levallois-perret", "neuilly-sur-seine"],
  },
  {
    slug: "paris-18", kind: "paris", name: "Paris 18e", full: "18e arrondissement de Paris", cp: "75018",
    min: 7800, max: 10500, trend: "hausse",
    intro: "Montmartre, Abbesses, Lamarck, Goutte-d'Or : le 18e est l'arrondissement des contrastes. Les pentes de la Butte comptent parmi les adresses les plus charmantes de Paris, tandis que l'est de l'arrondissement reste l'un des secteurs les plus accessibles de la capitale.",
    quartiers: [
      ["Abbesses / Montmartre", "Charme, vues, forte demande internationale."],
      ["Lamarck-Caulaincourt / Jules-Joffrin", "Résidentiel, familial, très recherché."],
      ["Clignancourt / Marcadet", "Plus accessible, en progression."],
      ["Goutte-d'Or / La Chapelle", "Prix les plus bas, secteur en transformation."],
    ],
    bati: "Immeubles anciens et haussmanniens, maisons et ateliers d'artistes sur la Butte, rues en pente et escaliers, immeubles faubouriens à l'est.",
    acheteurs: "Jeunes couples, primo-accédants, investisseurs, acquéreurs étrangers amoureux de Montmartre.",
    vigilance: "Vue dégagée sur Paris, ascenseur (ou son absence sur la Butte) et accessibilité font varier fortement la valeur. À l'est, la rue précise et l'environnement immédiat sont déterminants.",
    transports: "Lignes 2, 4, 12 et 13 (Abbesses, Lamarck–Caulaincourt, Jules Joffrin, Marcadet–Poissonniers, Barbès), funiculaire de Montmartre, tramway T3b.",
    faq: [
      { q: "Un appartement avec vue sur Paris à Montmartre vaut-il beaucoup plus ?", a: "Une vue dégagée est l'un des atouts les plus recherchés du 18e. Elle justifie une prime, à condition de la comparer à des ventes réelles de biens offrant des vues équivalentes." },
      { q: "Faut-il vendre maintenant dans l'est du 18e ?", a: "Le secteur bénéficie d'un rattrapage progressif, mais chaque rue a sa dynamique. Marie vous donne une lecture honnête du marché local pour choisir le bon moment et le bon prix." },
    ],
    near: ["paris-17", "paris-9", "paris-19", "paris-10"],
  },
  {
    slug: "paris-19", kind: "paris", name: "Paris 19e", full: "19e arrondissement de Paris", cp: "75019",
    min: 7300, max: 9700, trend: "hausse",
    intro: "Buttes-Chaumont, bassin de la Villette, parc de la Villette : le 19e est l'arrondissement le plus accessible de Paris en prix au m², mais aussi l'un de ceux qui ont le plus de potentiel. Ses grands espaces verts attirent de plus en plus de familles.",
    quartiers: [
      ["Buttes-Chaumont / Mouzaïa", "Parc, maisons de la Mouzaïa, secteur le plus recherché."],
      ["Bassin de la Villette / Jaurès", "Bords de l'eau, jeunes actifs, cinémas et restaurants."],
      ["Pont de Flandre / Parc de la Villette", "Plus accessible, projets urbains."],
      ["Place des Fêtes / Belleville", "Mixte, prix modérés, bonnes surfaces."],
    ],
    bati: "Grande diversité : immeubles anciens, maisons et villas (quartier de la Mouzaïa), nombreux ensembles des années 1960-70, constructions récentes le long du canal.",
    acheteurs: "Primo-accédants, familles cherchant de l'espace à prix contenu, investisseurs.",
    vigilance: "Les écarts sont forts entre les abords du parc des Buttes-Chaumont et certains grands ensembles. Charges, DPE et état de la copropriété sont examinés de près par les acheteurs.",
    transports: "Lignes 2, 5, 7, 7bis et 11 (Jaurès, Buttes Chaumont, Botzaris, Laumière, Place des Fêtes), RER E (Rosa Parks), tramway T3b.",
    faq: [
      { q: "Le 19e est-il l'arrondissement le moins cher de Paris ?", a: "C'est généralement celui où le prix au m² moyen est le plus bas. Mais les maisons de la Mouzaïa ou les appartements avec vue sur les Buttes-Chaumont se vendent bien au-dessus de cette moyenne." },
      { q: "Les maisons de la Mouzaïa s'estiment-elles comme les appartements ?", a: "Non : ce sont des biens rares, recherchés par des familles, qui se vendent au cas par cas. Leur valeur dépend de la surface, du jardin, de l'état et de la villa exacte ; une visite est indispensable." },
    ],
    near: ["paris-20", "paris-10", "paris-18"],
  },
  {
    slug: "paris-20", kind: "paris", name: "Paris 20e", full: "20e arrondissement de Paris", cp: "75020",
    min: 7400, max: 10000, trend: "hausse",
    intro: "Belleville, Ménilmontant, Père-Lachaise, Gambetta, Charonne : le 20e est un arrondissement populaire et créatif qui séduit de plus en plus de familles. Les prix y restent parmi les plus accessibles de Paris, avec une vraie dynamique de rattrapage.",
    quartiers: [
      ["Père-Lachaise / Gambetta", "Résidentiel, commerces, apprécié des familles."],
      ["Belleville / Ménilmontant", "Vues sur Paris, artistes, forte demande des jeunes actifs."],
      ["Charonne / Saint-Blaise", "Esprit village autour de l'église Saint-Germain-de-Charonne."],
      ["Saint-Fargeau / Porte de Bagnolet", "Plus accessible, pavillons et villas (la Campagne à Paris)."],
    ],
    bati: "Immeubles faubouriens, ateliers, maisons et villas (la Campagne à Paris), ensembles des années 1960-70, quelques haussmanniens autour de Gambetta et Pyrénées.",
    acheteurs: "Jeunes familles, primo-accédants, artistes, acheteurs venant de Montreuil ou du 11e.",
    vigilance: "Les hauteurs de Belleville offrent de belles vues, très valorisées ; à l'inverse, les grands ensembles et les axes bruyants se négocient davantage. Une maison ou un atelier doit être estimé au cas par cas.",
    transports: "Lignes 2, 3, 3bis, 9 et 11 (Belleville, Ménilmontant, Père Lachaise, Gambetta, Jourdain), tramway T3b.",
    faq: [
      { q: "Le 20e arrondissement a-t-il encore du potentiel ?", a: "Il fait partie des secteurs où les prix ont le plus progressé sur le long terme, avec encore une marge de rattrapage. Pour un vendeur, cela signifie une demande soutenue, à condition d'afficher un prix réaliste." },
      { q: "Un atelier d'artiste dans le 20e se vend-il facilement ?", a: "Oui, il a une clientèle passionnée, mais plus restreinte. Lumière, hauteur sous plafond, surface habitable réelle et usage déclaré doivent être parfaitement documentés." },
    ],
    near: ["paris-19", "paris-11", "paris-12", "montreuil"],
  },
];

export const IDF = [
  {
    slug: "neuilly-sur-seine", kind: "idf", name: "Neuilly-sur-Seine", cp: "92200", dept: "Hauts-de-Seine (92)",
    min: 8800, max: 12500, trend: "stable",
    intro: "Aux portes du 16e et du 17e, Neuilly-sur-Seine est l'une des communes les plus recherchées d'Île-de-France : cadre résidentiel, écoles réputées et accès immédiat à Paris comme à La Défense. Son marché est proche de celui de l'ouest parisien, avec une clientèle familiale et internationale.",
    quartiers: [
      ["Saint-James / Bagatelle", "Hôtels particuliers, villas, bois de Boulogne : l'adresse la plus prestigieuse."],
      ["Sablons", "Commerçant, familial, proche du métro."],
      ["Île de la Jatte", "Cadre unique au bord de la Seine, marché très étroit."],
      ["Bineau / Château", "Résidentiel, grands appartements, meilleur rapport prix/surface."],
    ],
    bati: "Immeubles bourgeois des années 1900-1930, résidences de standing des années 1960-70 avec parking et gardien, hôtels particuliers et maisons.",
    acheteurs: "Familles aisées, dirigeants travaillant à La Défense ou dans l'ouest parisien, expatriés de retour en France, acheteurs internationaux.",
    vigilance: "Entre une résidence des années 1970 avec parking et un immeuble ancien de caractère, les acheteurs ne raisonnent pas de la même façon. La proximité de la ligne 1 et du bois de Boulogne pèse fortement.",
    transports: "Métro ligne 1 (Les Sablons, Pont de Neuilly), bus vers Paris et La Défense, accès rapide au périphérique.",
    faq: [
      { q: "Neuilly est-il plus cher que le 16e arrondissement ?", a: "Les niveaux de prix sont comparables, avec des écarts selon les secteurs. Le quartier Saint-James et l'île de la Jatte peuvent dépasser les meilleures adresses du 16e ; d'autres secteurs sont plus accessibles." },
      { q: "Faut-il un parking pour bien vendre à Neuilly ?", a: "Ce n'est pas obligatoire, mais c'est un critère très demandé par les familles de la commune. Un appartement avec parking ou box se vend généralement plus vite, et l'estimation doit le valoriser explicitement." },
    ],
    near: ["paris-16", "paris-17", "levallois-perret", "courbevoie"],
  },
  {
    slug: "levallois-perret", kind: "idf", name: "Levallois-Perret", cp: "92300", dept: "Hauts-de-Seine (92)",
    min: 8000, max: 10500, trend: "stable",
    intro: "Commune parmi les plus denses de France, Levallois-Perret séduit par ses rues commerçantes, ses équipements et sa proximité immédiate avec le 17e arrondissement. Ses prix au m² comptent parmi les plus élevés des Hauts-de-Seine.",
    quartiers: [
      ["Centre / Hôtel de ville", "Commerces, marché, très demandé."],
      ["Bords de Seine / Île de la Jatte", "Vues sur Seine, résidences récentes, parc."],
      ["Anatole-France / Louise-Michel", "Proche du métro, familial, dynamique."],
      ["Villiers", "Résidentiel, proche de Neuilly et du 17e."],
    ],
    bati: "Beaucoup de constructions des années 1980 à 2000 issues de la rénovation urbaine, immeubles anciens autour de la rue Anatole-France, résidences récentes en bord de Seine.",
    acheteurs: "Jeunes familles, cadres de La Défense et de l'ouest parisien, acheteurs du 17e en quête d'espace ou de parking.",
    vigilance: "Le bâti récent offre souvent de bons DPE et des parkings, ce qui compte dans l'estimation. Les résidences avec services ou fortes charges doivent être comparées entre elles.",
    transports: "Métro ligne 3 (Anatole France, Louise Michel, Pont de Levallois–Bécon), Transilien L (Clichy–Levallois), ligne 14 à Porte de Clichy à proximité.",
    faq: [
      { q: "Levallois est-il aussi cher que Paris ?", a: "Levallois-Perret affiche des prix proches de ceux de plusieurs arrondissements parisiens, notamment du 17e. La présence fréquente d'un parking et de bons DPE dans le bâti récent explique en partie ce niveau." },
      { q: "Un bien avec parking se vend-il mieux à Levallois ?", a: "Oui, c'est un critère très recherché par les familles, qui l'intègrent souvent dans leur budget. Marie le valorise explicitement dans l'estimation et dans l'annonce." },
    ],
    near: ["paris-17", "neuilly-sur-seine", "courbevoie"],
  },
  {
    slug: "boulogne-billancourt", kind: "idf", name: "Boulogne-Billancourt", cp: "92100", dept: "Hauts-de-Seine (92)",
    min: 7300, max: 10000, trend: "stable",
    intro: "L'une des villes les plus peuplées d'Île-de-France, Boulogne-Billancourt offre un cadre de vie très recherché entre bois de Boulogne, Seine et quartiers commerçants. Son marché est vaste et contrasté, du nord résidentiel proche d'Auteuil au quartier du Trapèze, sur les anciens terrains Renault.",
    quartiers: [
      ["Boulogne Nord / Rothschild", "Proche du bois, hôtels particuliers, très prisé."],
      ["Centre / Jean-Jaurès", "Commerçant, familial, bien desservi."],
      ["Trapèze / Île Seguin", "Quartier neuf, bons DPE, parcs."],
      ["Billancourt / Point-du-Jour", "Mixte, proche du 16e et de la ligne 9."],
    ],
    bati: "Immeubles Art déco et années 1930 (patrimoine remarquable), maisons et hôtels particuliers au nord, immeubles récents au Trapèze, résidences des années 1960-70.",
    acheteurs: "Familles, cadres des sièges sociaux et des médias implantés à Boulogne, acheteurs du 15e et du 16e.",
    vigilance: "Les écarts sont importants entre le nord de la ville et certains secteurs de Billancourt. Les biens récents du Trapèze s'estiment différemment des appartements anciens, notamment au regard du DPE et des charges.",
    transports: "Métro lignes 9 et 10 (Marcel Sembat, Billancourt, Pont de Sèvres, Boulogne–Jean Jaurès, Boulogne–Pont de Saint-Cloud), tramway T2 à proximité, future ligne 15 Sud à Pont de Sèvres.",
    faq: [
      { q: "Quel est le quartier le plus cher de Boulogne-Billancourt ?", a: "Le nord de la ville, proche du bois de Boulogne et d'Auteuil, est traditionnellement le plus valorisé. Le Trapèze attire aussi une clientèle prête à payer pour du neuf bien isolé." },
      { q: "La future ligne 15 fait-elle monter les prix à Boulogne ?", a: "La gare Pont de Sèvres de la ligne 15 Sud améliorera les liaisons de banlieue à banlieue. C'est un argument de vente, mais l'estimation doit rester fondée sur les ventes réelles d'aujourd'hui." },
    ],
    near: ["paris-16", "issy-les-moulineaux", "saint-cloud", "paris-15"],
  },
  {
    slug: "issy-les-moulineaux", kind: "idf", name: "Issy-les-Moulineaux", cp: "92130", dept: "Hauts-de-Seine (92)",
    min: 6800, max: 9000, trend: "stable",
    intro: "Au sud-ouest de Paris, Issy-les-Moulineaux s'est transformée en pôle économique et résidentiel : sièges d'entreprises, écoquartiers et bords de Seine. La ville attire les familles et les actifs qui cherchent plus d'espace qu'à Paris sans s'éloigner du 15e.",
    quartiers: [
      ["Centre-ville / Corentin-Celton", "Commerces, métro 12, très demandé."],
      ["Fort d'Issy", "Écoquartier, vues, bons DPE."],
      ["Issy Val-de-Seine / Bords de Seine", "Bureaux et résidences récentes, tramway."],
      ["Hauts d'Issy", "Résidentiel, pavillons, familial."],
    ],
    bati: "Résidences récentes et écoquartiers, immeubles des années 1970-90, pavillons sur les hauteurs, quelques immeubles anciens en centre-ville.",
    acheteurs: "Familles, cadres travaillant dans les sièges sociaux de la ville, acheteurs du 15e arrondissement.",
    vigilance: "Le bâti récent offre souvent de bons DPE et des parkings ; les résidences plus anciennes doivent être comparées entre elles. La proximité du métro 12 et du RER C fait une vraie différence.",
    transports: "Métro ligne 12 (Corentin Celton, Mairie d'Issy), RER C (Issy, Issy Val de Seine), tramway T2, future ligne 15 Sud.",
    faq: [
      { q: "Issy-les-Moulineaux est-elle moins chère que le 15e ?", a: "En moyenne oui, pour des surfaces souvent plus grandes et un bâti plus récent. Les meilleurs biens (vue, terrasse, écoquartier) se rapprochent toutefois des prix parisiens voisins." },
      { q: "Les appartements neufs d'Issy se revendent-ils bien ?", a: "Oui, grâce à leurs bons DPE, leurs extérieurs et leurs parkings. Leur prix se compare avant tout aux reventes récentes dans les mêmes résidences ou écoquartiers, plutôt qu'à l'ancien." },
    ],
    near: ["paris-15", "boulogne-billancourt", "saint-cloud"],
  },
  {
    slug: "saint-cloud", kind: "idf", name: "Saint-Cloud", cp: "92210", dept: "Hauts-de-Seine (92)",
    min: 5800, max: 8500, trend: "stable",
    intro: "Dominant la Seine face au bois de Boulogne, Saint-Cloud est une ville résidentielle, verte et familiale, réputée pour son domaine national et ses établissements scolaires. Son marché mêle appartements bourgeois et belles maisons avec jardin.",
    quartiers: [
      ["Centre / Village", "Commerces, rues anciennes, esprit village."],
      ["Montretout", "Maisons de caractère, vues sur Paris."],
      ["Val d'Or", "Résidentiel, gare, familial."],
      ["Bords de Seine / Pont de Saint-Cloud", "Proche de Boulogne, desserte par le tramway T2."],
    ],
    bati: "Maisons bourgeoises et meulières, résidences de standing des années 1960-80 dans des parcs, immeubles anciens en centre-ville.",
    acheteurs: "Familles, cadres de La Défense et de Boulogne, Parisiens en quête de verdure.",
    vigilance: "Pour les maisons, jardin, vue et état général pèsent autant que la surface. Les résidences avec parc et gardien se comparent entre elles, en tenant compte des charges.",
    transports: "Transilien L et U (Saint-Cloud, Le Val d'Or), tramway T2 (Parc de Saint-Cloud), métro ligne 10 à Boulogne–Pont de Saint-Cloud.",
    faq: [
      { q: "Une maison à Saint-Cloud s'estime-t-elle au m² ?", a: "Pas seulement : le terrain, la vue, l'exposition, l'état et la rue comptent énormément. Le prix au m² sert de repère, mais seule une visite permet une estimation fiable." },
      { q: "Qui achète à Saint-Cloud ?", a: "Principalement des familles venant de Paris ou de Boulogne, attirées par le cadre vert, les écoles et l'accès à La Défense. Elles recherchent des surfaces familiales, un extérieur et le calme." },
    ],
    near: ["boulogne-billancourt", "rueil-malmaison", "versailles"],
  },
  {
    slug: "courbevoie", kind: "idf", name: "Courbevoie", cp: "92400", dept: "Hauts-de-Seine (92)",
    min: 6000, max: 8300, trend: "stable",
    intro: "Entre La Défense et les bords de Seine, Courbevoie offre un marché très varié : appartements récents près du quartier d'affaires, immeubles anciens autour du centre et secteur recherché de Bécon-les-Bruyères.",
    quartiers: [
      ["Bécon-les-Bruyères", "Résidentiel, pavillons et immeubles de caractère, très familial."],
      ["Centre / Hôtel de ville", "Commerces, parc de Bécon à proximité."],
      ["Faubourg de l'Arche", "Immeubles récents au pied de La Défense, clientèle d'actifs."],
      ["Gare de Courbevoie / Marceau", "Mixte, proche des transports, bon rapport qualité-prix."],
    ],
    bati: "Tours et résidences récentes près de La Défense, immeubles anciens et pavillons à Bécon, résidences des années 1970.",
    acheteurs: "Actifs travaillant à La Défense, jeunes familles, investisseurs locatifs.",
    vigilance: "La proximité de La Défense garantit une forte demande locative, mais certains immeubles ont des charges élevées. Bécon se valorise différemment, avec une clientèle familiale.",
    transports: "RER A et ligne 1 (La Défense), Transilien L (Bécon-les-Bruyères, Courbevoie), tramway T2, future ligne 15 Ouest.",
    faq: [
      { q: "Bécon-les-Bruyères est-il le quartier le plus recherché de Courbevoie ?", a: "C'est l'un des plus prisés des familles, pour son ambiance résidentielle et sa gare. Les biens de caractère et les maisons y trouvent facilement preneur lorsqu'ils sont bien estimés." },
      { q: "Vendre un studio près de La Défense : à qui ?", a: "Surtout à des investisseurs et à de jeunes actifs. Le DPE, les charges et le rendement locatif sont leurs premiers critères : l'estimation doit les intégrer." },
    ],
    near: ["neuilly-sur-seine", "levallois-perret", "rueil-malmaison"],
  },
  {
    slug: "rueil-malmaison", kind: "idf", name: "Rueil-Malmaison", cp: "92500", dept: "Hauts-de-Seine (92)",
    min: 4900, max: 7000, trend: "stable",
    intro: "Ville verte et étendue au bord de la Seine, Rueil-Malmaison séduit les familles par ses maisons, ses parcs et son cadre de vie, à quelques minutes de La Défense. Son marché est très segmenté entre quartiers pavillonnaires, centre-ville et bords de Seine.",
    quartiers: [
      ["Centre-ville", "Commerces, marché, appartements anciens."],
      ["Buzenval / Plateau", "Pavillons et maisons, très familial."],
      ["Rueil-sur-Seine", "Résidences récentes, bords de Seine."],
      ["Malmaison / Bois-Préau", "Proche du château, cadre verdoyant."],
    ],
    bati: "Maisons individuelles et pavillons, résidences des années 1960 à aujourd'hui, écoquartiers récents, immeubles anciens en centre-ville.",
    acheteurs: "Familles avec enfants, cadres de La Défense, Parisiens en quête de jardin.",
    vigilance: "Pour les maisons, la taille du terrain, l'exposition et la proximité des écoles et du RER sont déterminantes. Les appartements se comparent quartier par quartier.",
    transports: "RER A (Rueil-Malmaison), nombreuses lignes de bus vers La Défense, future ligne 15 Ouest.",
    faq: [
      { q: "Maison ou appartement : quel marché à Rueil-Malmaison ?", a: "Les deux sont actifs. Les maisons familiales proches des écoles et du RER A sont très recherchées ; les appartements récents avec extérieur séduisent les couples et les jeunes retraités." },
      { q: "La proximité du RER A change-t-elle le prix ?", a: "Oui, pour les appartements comme pour les maisons : les acheteurs qui travaillent à La Défense ou à Paris regardent en priorité le temps de trajet à pied jusqu'à la gare." },
    ],
    near: ["saint-cloud", "courbevoie", "saint-germain-en-laye"],
  },
  {
    slug: "vincennes", kind: "idf", name: "Vincennes", cp: "94300", dept: "Val-de-Marne (94)",
    min: 7500, max: 10000, trend: "stable",
    intro: "Aux portes du 12e et du 20e, Vincennes est l'une des villes les plus recherchées de l'Est parisien : château, bois, rues commerçantes et excellente desserte. Ses prix se rapprochent de ceux de plusieurs arrondissements parisiens.",
    quartiers: [
      ["Centre / Rue du Midi", "Commerces, immeubles anciens, très demandé."],
      ["Château / Bois", "Proche du château et du bois, adresse la plus recherchée."],
      ["Ouest / Bérault", "Proche de Paris et de la ligne 1."],
      ["Est / Diderot", "Résidentiel, un peu plus accessible."],
    ],
    bati: "Immeubles anciens et bourgeois (fin XIXe-début XXe siècle), quelques maisons, résidences des années 1960-80.",
    acheteurs: "Familles parisiennes cherchant plus d'espace et de verdure, cadres, acquéreurs de Saint-Mandé et du 12e.",
    vigilance: "La proximité du bois, de la ligne 1 et du RER A fait la différence. Les appartements anciens de caractère avec balcon et ascenseur sont particulièrement recherchés.",
    transports: "Métro ligne 1 (Bérault, Château de Vincennes), RER A (Vincennes).",
    faq: [
      { q: "Vincennes est-elle plus chère que le 12e arrondissement ?", a: "Les niveaux sont proches, et certains biens de Vincennes proches du bois dépassent les prix de l'est du 12e. La commune bénéficie d'une forte demande de familles venant de Paris." },
      { q: "Quels biens se vendent le plus vite à Vincennes ?", a: "Les 3 et 4 pièces familiaux dans l'ancien, avec ascenseur, proches du centre et des écoles. Bien estimés, ils trouvent généralement preneur rapidement." },
    ],
    near: ["saint-mande", "montreuil", "nogent-sur-marne", "paris-12"],
  },
  {
    slug: "saint-mande", kind: "idf", name: "Saint-Mandé", cp: "94160", dept: "Val-de-Marne (94)",
    min: 7900, max: 10500, trend: "stable",
    intro: "Petite ville résidentielle nichée entre le 12e arrondissement et le bois de Vincennes, Saint-Mandé offre une qualité de vie très recherchée : calme, verdure et accès immédiat à Paris. Son marché est étroit et ses prix au m² parmi les plus élevés du Val-de-Marne.",
    quartiers: [
      ["Centre / Mairie", "Commerces, immeubles bourgeois."],
      ["Lisière du bois / Lac", "Vues sur le bois, adresse très prisée."],
      ["Saint-Mandé Nord", "Proche de la ligne 1 et de Vincennes, résidentiel."],
    ],
    bati: "Immeubles bourgeois du début du XXe siècle, résidences de standing en lisière du bois, quelques maisons.",
    acheteurs: "Familles, professions libérales, Parisiens de l'Est cherchant un cadre plus calme.",
    vigilance: "L'offre est rare : chaque vente compte et les comparaisons doivent être faites avec soin. Une vue sur le bois ou le lac est un atout majeur.",
    transports: "Métro ligne 1 (Saint-Mandé), RER A à Vincennes, proximité immédiate du 12e arrondissement.",
    faq: [
      { q: "Pourquoi Saint-Mandé est-elle si recherchée ?", a: "Pour son cadre calme en bordure du bois de Vincennes, sa taille humaine et son accès direct à Paris par la ligne 1. L'offre étant limitée, les biens bien estimés se vendent vite." },
      { q: "Comment estimer un bien quand il y a peu de ventes comparables ?", a: "C'est tout l'enjeu d'un petit marché comme Saint-Mandé. Marie croise les ventes réelles de la commune, celles de Vincennes et de l'est du 12e, et sa visite du bien, pour proposer un prix argumenté." },
    ],
    near: ["vincennes", "paris-12", "nogent-sur-marne"],
  },
  {
    slug: "nogent-sur-marne", kind: "idf", name: "Nogent-sur-Marne", cp: "94130", dept: "Val-de-Marne (94)",
    min: 5500, max: 7800, trend: "stable",
    intro: "Au bord de la Marne, Nogent-sur-Marne offre le cadre d'une ville résidentielle, avec son port de plaisance, ses guinguettes et ses belles maisons de bord de Marne. Bien reliée à Paris par le RER A et le RER E, elle attire les familles de l'Est parisien.",
    quartiers: [
      ["Centre / Grande Rue", "Commerces, marché, appartements."],
      ["Bords de Marne / Port", "Maisons de caractère, vues sur l'eau."],
      ["Baltard / Gare RER A", "Proche du RER, résidentiel."],
    ],
    bati: "Maisons bourgeoises et meulières, immeubles anciens en centre-ville, résidences des années 1970 à nos jours.",
    acheteurs: "Familles parisiennes cherchant une maison ou un grand appartement, cadres, jeunes retraités.",
    vigilance: "Pour les biens en bord de Marne, la vue est très valorisée ; l'état des risques (zone inondable le long de la rivière) doit être présenté clairement. La distance à pied du RER est un critère clé.",
    transports: "RER A (Nogent-sur-Marne), RER E (Nogent–Le Perreux), autoroutes A4 et A86.",
    faq: [
      { q: "Les maisons en bord de Marne sont-elles concernées par le risque d'inondation ?", a: "Certaines parcelles sont situées en zone réglementée par un plan de prévention du risque inondation. L'information figure dans l'état des risques remis à l'acquéreur ; elle doit être prise en compte dans l'estimation, sans être dramatisée." },
      { q: "Nogent-sur-Marne attire-t-elle les Parisiens ?", a: "Oui, notamment des familles de l'Est parisien et de Vincennes qui recherchent plus d'espace, un jardin ou une vue sur l'eau, tout en restant à quelques minutes de Paris en RER." },
    ],
    near: ["vincennes", "saint-mande", "montreuil"],
  },
  {
    slug: "montreuil", kind: "idf", name: "Montreuil", cp: "93100", dept: "Seine-Saint-Denis (93)",
    min: 4800, max: 7300, trend: "hausse",
    intro: "Limitrophe du 20e arrondissement, Montreuil est devenue l'une des villes les plus dynamiques de l'Est parisien : ateliers d'artistes, maisons avec jardin, marché de la Croix-de-Chavaux et prolongement de la ligne 11. Le Bas-Montreuil, proche de Paris, en est le secteur le plus recherché.",
    quartiers: [
      ["Bas-Montreuil", "Proche du 20e, lofts et ateliers, très demandé."],
      ["Croix-de-Chavaux / Centre", "Commerces, marché, métro 9."],
      ["Murs-à-Pêches / Saint-Antoine", "Pavillonnaire, jardins, esprit village."],
      ["Hauts de Montreuil", "Plus accessible, desservi par le prolongement de la ligne 11."],
    ],
    bati: "Maisons de ville, pavillons, anciens ateliers et lofts, immeubles faubouriens, grands ensembles sur les hauteurs.",
    acheteurs: "Familles parisiennes cherchant une maison ou plus d'espace, créatifs, primo-accédants.",
    vigilance: "Les écarts sont importants entre le Bas-Montreuil et les Hauts. Pour une maison ou un loft, la surface habitable réelle, le jardin et la régularité administrative (changement d'usage d'un atelier) doivent être documentés.",
    transports: "Métro ligne 9 (Robespierre, Croix de Chavaux, Mairie de Montreuil), ligne 11 (Montreuil–Hôpital, La Dhuys), ligne 1 à proximité.",
    faq: [
      { q: "Le Bas-Montreuil est-il aussi cher que le 20e ?", a: "Il s'en rapproche pour les biens de qualité (lofts, maisons rénovées), tout en restant généralement plus accessible. C'est l'une des alternatives les plus recherchées par les familles de l'Est parisien." },
      { q: "Le prolongement de la ligne 11 a-t-il changé le marché des Hauts de Montreuil ?", a: "Il a nettement amélioré la desserte de secteurs jusque-là éloignés du métro. Cela soutient la demande, mais chaque rue garde sa propre dynamique : l'estimation reste fondée sur les ventes réelles du quartier." },
    ],
    near: ["paris-20", "vincennes", "nogent-sur-marne"],
  },
  {
    slug: "versailles", kind: "idf", name: "Versailles", cp: "78000", dept: "Yvelines (78)",
    min: 5800, max: 9000, trend: "stable",
    intro: "Ville royale et préfecture des Yvelines, Versailles conjugue patrimoine, établissements scolaires réputés et cadre de vie familial. Son marché est porté par une demande solide et fidèle, avec des quartiers aux identités très marquées.",
    quartiers: [
      ["Notre-Dame", "Quartier historique et commerçant, marché, très recherché."],
      ["Saint-Louis", "Charme ancien, cathédrale, potager du Roi."],
      ["Montreuil", "Résidentiel, grands appartements et maisons."],
      ["Porchefontaine / Chantiers", "Plus accessible, gares, familial."],
    ],
    bati: "Hôtels particuliers et immeubles XVIIe-XVIIIe, immeubles bourgeois du XIXe siècle, maisons avec jardin, résidences des années 1960-70.",
    acheteurs: "Familles attachées aux établissements scolaires, cadres travaillant à Paris, à La Défense ou à Saint-Quentin, retraités.",
    vigilance: "Chaque quartier a sa clientèle ; le secteur sauvegardé impose des contraintes sur les travaux. La proximité d'une gare vers Paris et des écoles est très valorisée.",
    transports: "RER C (Versailles Château Rive Gauche), Transilien L, N et U (Versailles Rive Droite, Versailles Chantiers).",
    faq: [
      { q: "Pourquoi Versailles attire-t-elle autant de familles ?", a: "Pour son patrimoine, son offre scolaire réputée, ses espaces verts et ses liaisons ferroviaires vers Paris depuis trois gares. Cette demande familiale soutient les prix des grands appartements et des maisons." },
      { q: "Notre-Dame ou Saint-Louis : quel quartier est le plus cher ?", a: "Les deux quartiers historiques se situent dans le haut de la fourchette versaillaise, avec des écarts qui tiennent surtout à l'immeuble, à l'étage et à la proximité du château ou du marché. Une estimation au cas par cas est indispensable." },
    ],
    near: ["saint-cloud", "saint-germain-en-laye", "rueil-malmaison"],
  },
  {
    slug: "saint-germain-en-laye", kind: "idf", name: "Saint-Germain-en-Laye", cp: "78100", dept: "Yvelines (78)",
    min: 5500, max: 8300, trend: "stable",
    intro: "Au terminus du RER A, Saint-Germain-en-Laye offre un cadre prestigieux entre forêt, château et terrasse dominant la Seine. Ville bourgeoise et internationale, notamment grâce à son lycée international, elle attire des familles françaises et expatriées.",
    quartiers: [
      ["Centre historique / Château", "Rues piétonnes, immeubles anciens, très demandé."],
      ["Secteur du lycée international", "Maisons et résidences, familles expatriées."],
      ["Lisière de la forêt", "Maisons de caractère, cadre verdoyant."],
      ["Fourqueux / Bel-Air", "Pavillonnaire, plus accessible."],
    ],
    bati: "Hôtels particuliers et immeubles anciens en centre-ville, maisons bourgeoises, résidences des années 1960-80.",
    acheteurs: "Familles, expatriés et acheteurs internationaux, cadres de La Défense et de l'ouest parisien.",
    vigilance: "Proximité du RER A et du centre, calme, jardin : les critères classiques d'une ville familiale. La clientèle internationale est un atout pour les biens de standing.",
    transports: "RER A (Saint-Germain-en-Laye), tramway T13, accès A13 et A14.",
    faq: [
      { q: "Les acheteurs internationaux sont-ils nombreux à Saint-Germain-en-Laye ?", a: "Oui, la présence du lycée international et la proximité de La Défense attirent de nombreuses familles expatriées. Le réseau Leggett permet de toucher cette clientèle en complément des portails français." },
      { q: "Comment vendre une maison à Saint-Germain-en-Laye au bon prix ?", a: "En s'appuyant sur des ventes réellement comparables (quartier, terrain, état) plutôt que sur un prix au m² moyen. Marie visite le bien, analyse les ventes récentes et vous présente une fourchette argumentée." },
    ],
    near: ["versailles", "rueil-malmaison", "saint-cloud"],
  },
];

export const ALL_LOCATIONS = [...PARIS, ...IDF];

export const getLocation = (slug) => ALL_LOCATIONS.find((l) => l.slug === slug);

// "16e" pour Paris, nom de commune sinon
export const shortName = (loc) => (loc.kind === "paris" ? loc.name.replace("Paris ", "") : loc.name);

// "dans le 16e arrondissement de Paris" / "à Neuilly-sur-Seine"
export const inName = (loc) => (loc.kind === "paris" ? `dans le ${loc.full}` : `à ${loc.name}`);

export const fmtEur = (n) => `${n.toLocaleString("fr-FR").replace(/ | /g, " ")} €`;
